config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :user, skip: :registrations, controllers: {
    sessions: 'backend/devise/sessions',
    passwords: 'backend/devise/passwords'
  }
  devise_scope :user do
    get '/sign_in', to: 'backend/devise/sessions#new', as: 'sign_in'
  end

  mount Ckeditor::Engine => '/ckeditor'

  scope '/admin', module: :backend do
    get '/', to: 'dashboard#index', as: :dashboard

    resources :posts,      except: [:show]
    resources :previews,   only: [:create]
    resources :categories
    resources :tags
    resources :comments, except: %i[show new create]
    resources :activities
    resources :news, except: [:show]
    resources :users

    mount Resque::Server.new, at: 'resque'
  end

  scope module: :frontend do
    root to: 'webs#index'

    scope module: :webs do
      get  'about_us'
      get  'contact_us'
      post 'send_email'
    end

    post '/',                           to: 'webs#index'
    post '/:post_id/comment',           to: 'comments#create', as: :post_comments
    get  '/preview/:token',             to: 'previews#show'
    get  '/categories',                 to: 'categories#index'
    get  '/tags',                       to: 'tags#index'
    get  '/tags/:name',                 to: 'tags#show', as: :frontend_tag
    get  '/activities',                 to: 'activities#index'
    get  '/activities/:id',             to: 'activities#show', as: :frontend_activity
    get  '/news',                       to: 'news#index',      as: :frontend_news
    get  '/date/:year/:month',          to: 'webs#date'
    get  '/wp-content/uploads/:handle', to: 'webs#wp_content'
    get  '/search',                     to: 'search#index',    as: :search
    get  '/:id/:handle',                to: 'posts#show',      as: :frontend_post
    get  '/:handle',                    to: 'categories#show', as: :frontend_category

    match '*path' => redirect('/'), via: %i[get post]
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/frontend/activities_controller.rb
class Frontend::ActivitiesController < Frontend::ApplicationController

  def index
    @activities = Activity.is_public.page params[:page]
  end

  def show
    @activity = Activity.is_public.find params[:id].to_i
    redirect_to root_path, :flash => { error: "目錄已移除" } and return unless @activity
  end

end

app/controllers/frontend/application_controller.rb
class Frontend::ApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :prepare_meta_tags, if: -> { request.get? }
  layout 'frontend_application'

  def prepare_meta_tags(options = {})
    site_name   = Settings.name
    title       = options[:title] || Settings.name
    description = options[:description] || Settings.description
    keywords    = "#{options[:keywords]}, #{Settings.keywords}".strip.split(/, */).reject { |e| e.empty? }
    image       = options[:image].present? ? "#{Settings.url}#{options[:image]}" : "#{Settings.url}/images/logo.jpg"
    current_url = request.url

    hash = {
      site: site_name,
      title: title,
      image: image,
      description: description,
      keywords: keywords,
      og: {
        url: current_url,
        site_name: site_name,
        title: title,
        image: image,
        description: description,
        type: options[:og_type] || 'website'
      },
      icon: [
        { href: '/images/favicon.ico' },
        { href: '/images/apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' }
      ],
      alternate: [
        { href: Settings.rss, type: 'application/rss+xml', title: 'RSS' }
      ],
      viewport: 'width=device-width, initial-scale=1.0'
    }

    set_meta_tags hash
  end
end

app/controllers/frontend/categories_controller.rb
class Frontend::CategoriesController < Frontend::ApplicationController

  def index
    @categories = Category.includes(:posts).publish_post.page params[:page]
  end

  def show
    @category = Category.find_by_handle params[:handle]
    redirect_to root_path, :flash => { error: "目錄已移除" } and return unless @category
    @recent_posts = @category.posts.publish.page params[:page]
  end

end

app/controllers/frontend/comments_controller.rb
class Frontend::CommentsController < Frontend::ApplicationController

  def create
    errors = %w(驗證碼錯誤) unless check_grecaptcha

    @post = Post.find params[:post_id].to_i
    @comment = @post.comments.build comment_params
    if errors.blank? && @comment.save
      render json: { url: frontend_post_path(@post.id, @post.handle) + "#comment-#{@comment.id}" }
    else
      errors ||= []
      errors += @comment.errors.full_messages
      render json: { message: errors }, status: 404
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :url, :content)
  end

end

app/controllers/frontend/news_controller.rb
class Frontend::NewsController < Frontend::ApplicationController

  def index
    @news = News.page params[:page]
  end

end

app/controllers/frontend/posts_controller.rb
class Frontend::PostsController < Frontend::ApplicationController

  def show
    @post = Post.includes(:comments, :post_meta).publish.find_by_handle params[:handle]
    redirect_to root_path, :flash => { error: "目錄已移除" } and return unless @post
    prepare_meta_tags title: @post.title,
                      description: @post.post_meta.description || @post.excerpt,
                      keywords: @post.post_meta.keywords,
                      og_type: 'article',
                      image: @post.main_picture_url
  end

end

app/controllers/frontend/previews_controller.rb
class Frontend::PreviewsController < Frontend::ApplicationController

  def show
    @post = Preview.find_by_token params[:token]
    redirect_to root_path, :flash => { error: "目錄已移除" } and return unless @post
  end

end

app/controllers/frontend/search_controller.rb
class Frontend::SearchController < Frontend::ApplicationController
  before_action :validate

  def index
    @posts = Post.publish.search(@query).result(:distinct => true).page params[:page]
  end

  protected

  def validate
    query_string = params[:q].present? ? params[:q].gsub(/\\|\'|\/|\?/, "") : ""
    @query = { title_or_content_cont: query_string }
  end

end

app/controllers/frontend/tags_controller.rb
class Frontend::TagsController < Frontend::ApplicationController

  def index
    @tags = Tag.includes(:posts).publish_post.page params[:page]
  end

  def show
    @tag = Tag.find_by_name params[:name]
    redirect_to root_path, :flash => { error: "目錄已移除" } and return unless @tag
    @recent_posts = @tag.posts.publish.page params[:page]
  end

end

app/controllers/frontend/webs_controller.rb
class Frontend::WebsController < Frontend::ApplicationController

  def index
    @activity = Activity.is_public.where("start_at > ?", Time.now).order('start_at asc').first
    @activity = Activity.is_public.where("start_at < ?", Time.now).first unless @activity

    respond_to do |format|
      format.html
      format.all { render file: 'public/404.html', status: 404 }
    end
  end

  def about_us
  end

  def contact_us
  end

  def date
    @begin_day = Date.new params[:year].to_i, params[:month].to_i, 1
    @recent_posts = Post.publish.where(posted_at: @begin_day..@begin_day + 1.month).page params[:page]
  end

  def send_email
    Resque.enqueue(MailJob, params)
    redirect_to contact_us_path, flash: { success: "發送成功" } and return
  end

  def wp_content
    handle = CGI::unescape request.original_fullpath.split('?').first.split('/').last
    redirect_to Ckeditor::Asset.find_by_data_name(handle).url
  rescue
    redirect_to root_path, flash: { warning: "檔案不存在" }
  end

end

app/helpers/frontend_helper.rb
module FrontendHelper

  def post_year_month_list(length)
    Post.publish.select(:posted_at).
      group_by { |t| t.posted_at.beginning_of_month.to_time }.keys[0..length - 1].
      map { |t| t.to_s.split("-")[0..1] }
  end

  def content_area(post)
    link = link_to "Continue Reading...", frontend_post_path(post.id, post.handle), class: "margin-left-10"
    content_tag :p do
      "#{post.excerpt}#{link}".html_safe
    end
  end

  def gtag
    %Q(
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-59284592-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-59284592-1');
      </script>
    )
  end

end

app/views/frontend/webs/about_us.html.slim
- title keywords description "關於田調團"
.container-fluid.bottom-buffer
  .row
    .col-md-9.col-xs-12
      header.entry-header
        h2 關於田調團
      .entry-content
        = image_tag "tfg.jpg", class: "top-buffer bottom-buffer"
        h4
          b 我們是誰
        p.bottom-buffer
          | 一群來自台中或認同台中的青年，不論身在何處，我們討論更好的城市想像，並著手實踐。
        h4
          b 我們的理念
        p.bottom-buffer
          | 一座城市的發展需要市民共同形塑和參與，才能注入民主與活力。然而，過往的城市發展在制度面與執行面都排除了市民參與的可能。我們的核心價值是在台中落實「市民城市與權利」。
        h4
          b 我們的社會行動
        p
          | 為了使台中成為有更多元聲音的城市，我們目前嘗試以下五種行動：
          ul
            li 踏查與訪談：透過走入在地與居民直接訪調的過程，呈現以居民為主體台中多元的樣貌；
            li 研究：彙整相關資料並擬定研究報告以提供相關部門參考當前台中發展的現況；
            li 講座分享：藉由講座分享台中故事，讓更多人了解台中的現況與困境，理解城市不同樣貌與多元特性；
            li 社區聯繫：透過田調與社區建立關係網路，深入在地社群，了解各社區與城市之間的交互關係；
            li 活動：田調團也不定期的舉辦研討活動，包含重劃營隊、區域計畫工作坊等等。
            li 希望透過多元的社會行動，能夠建構出更美好的城市社會，讓台中呈現自己的聲音與發展的想像。歡迎一起加入我們！

    #sidebar.col-md-3.col-xs-12
      = render 'frontend/templates/time_list'
      = render 'frontend/templates/recent_posts'
      = render 'frontend/templates/recent_comments'

app/views/frontend/webs/contact_us.html.slim
- title keywords description "聯絡資訊"
.container-fluid.bottom-buffer
  .row
    .col-md-6.col-xs-12
      h2 聯絡資訊
      hr
      p
        | 結合熱愛臺中、關心臺中，用自己的腳去破除主流論述，看到屬於臺中真正的日常生活，論述出屬於臺中的故事。
        ul.list-unstyled
          li style="padding: 10px;"
            i.glyphicon.glyphicon-home.pull-left style="margin-right: 5px;"
            | Facebook：
            a href="https://www.facebook.com/taichungfieldwork"
              = Settings.name
          li style="padding: 10px;"
            i.glyphicon.glyphicon-envelope.pull-left style="margin-right: 5px;"
            | 聯絡信箱：
            a href="mailto: info@taichung-fieldwork.org"
              | info@taichung-fieldwork.org

    .col-md-6.col-xs-12
      h2 聯絡我們
      hr
      p
        = form_tag send_email_path, :method => :post, class: "form-horizontal"
          .form-group
            .col-md-12
              = text_field_tag "name", nil, placeholder: "姓名", class: "form-control", required: true
          .form-group
            .col-md-12
              = email_field_tag "email", nil, placeholder: "Email", class: "form-control", required: true
          .form-group
            .col-md-12
              = text_field_tag "subject", nil, placeholder: "主旨", class: "form-control", required: true
          .form-group
            .col-md-12
              = text_area_tag "content", nil, placeholder: "內容", row: 5, class: "form-control", required: true
          .form-group
            .col-md-12
              = submit_tag "送出", class: "btn btn-default"

app/views/frontend/webs/date.html.slim
- title "彙整：#{@begin_day.strftime('%m月 %Y')}"
.container-fluid.bottom-buffer
  .row
    .col-md-12
      header.entry-header.bottom-buffer
        h2
          = "彙整：#{@begin_day.strftime('%m月 %Y')}"
      = render partial: 'frontend/templates/post_list', locals: { recent_posts: @recent_posts }

      .row.text-center
        = paginate @recent_posts

app/views/frontend/webs/index.html.slim
.container-fluid
  ul.bxslider
    li
      a href="/city-story"
        = image_tag "banner01.jpg"
        .description
          | 攝於十三期重劃區，已搬離的居民在周末時回到村子，
          br 再看一眼即將拆除的家，他們將未來全寄望在土地的增值上
    li
      a href="/city-story"
        = image_tag "banner02.jpg"
        .description
          | 攝於香港北角
          br 與台灣城市面臨開發危機，市民文化與常民生活該何去何從呢?
          | 一起跟著臺中城市發展田調團來關注港台交流吧!

  .row.bottom-buffer
    #equalheight
      .col-md-4.col-xs-12
        .ehdiv
          .row
            .col-md-1.col-xs-1
            .col-md-10.col-xs-10.inner-box
              h3.one-line-solgan
                | 近期活動
              = content_tag :span, @activity.try(:name), class: "one-line-solgan"
              - if @activity
                p
                  ul.text-left
                    li
                      | 時間：
                      = @activity.start_at.strftime("%Y-%m-%d %H:%M").sub(" 00:00", "")
                    - if @activity.location.present?
                      li
                        | 地點：
                        = @activity.location
                    li
                      | 聯絡方式：
                      a href="mailto: info@taichung-fieldwork.org" info@taichung-fieldwork.org
                    - if @activity.link.present?
                      li
                        = link_to "參考連結", @activity.link, target: "_blank"
                  = link_to "Read More ...", frontend_activity_path(@activity)
        .bottom-padding
      .col-md-4.col-xs-12
        .ehdiv
          .row
            .col-md-1.col-xs-1
            .col-md-10.col-xs-10.inner-box
              h3 我們是誰
              p 一群來自台中或認同台中的青年，不論身在何處，我們討論更好的城市想像，並著手實踐。
              p 一座城市的發展需要市民共同形塑和參與，才能注入民主與活力。然而，過往的城市發展在制度面與執行面都排除了市民參與的可能。我們的核心價值是在台中落實「市民城市與權利」。
              a href="/about_us"  Read More ...
        .bottom-padding
      .col-md-4.col-xs-12
        .ehdiv
          .row
            .col-md-.col-xs-1
            .col-md-10.col-xs-10.inner-box
              - post = Post.publish.first
              - if post
                h3.one-line-solgan
                  = post.title
                p
                  = post.summary
                = link_to "Read More ...", frontend_post_path(post.id, post.handle)
        .bottom-padding