config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :user, skip: :registrations, controllers: {
    sessions: 'backend/devise/sessions',
    passwords: 'backend/devise/passwords'
  }
  devise_scope :user do
    get '/sign_in', to: 'backend/devise/sessions#new', as: 'sign_in'
  end

  mount Ckeditor::Engine => '/ckeditor'

  scope '/admin', module: :backend do
    get '/', to: 'dashboard#index', as: :dashboard

    resources :posts,      except: [:show]
    resources :previews,   only: [:create]
    resources :categories
    resources :tags
    resources :comments, except: %i[show new create]
    resources :activities
    resources :news, except: [:show]
    resources :users

    mount Resque::Server.new, at: 'resque'
  end

  scope module: :frontend do
    root to: 'webs#index'

    scope module: :webs do
      get  'about_us'
      get  'contact_us'
      post 'send_email'
    end

    post '/',                           to: 'webs#index'
    post '/:post_id/comment',           to: 'comments#create', as: :post_comments
    get  '/preview/:token',             to: 'previews#show'
    get  '/categories',                 to: 'categories#index'
    get  '/tags',                       to: 'tags#index'
    get  '/tags/:name',                 to: 'tags#show', as: :frontend_tag
    get  '/activities',                 to: 'activities#index'
    get  '/activities/:id',             to: 'activities#show', as: :frontend_activity
    get  '/news',                       to: 'news#index',      as: :frontend_news
    get  '/date/:year/:month',          to: 'webs#date'
    get  '/wp-content/uploads/:handle', to: 'webs#wp_content'
    get  '/search',                     to: 'search#index',    as: :search
    get  '/:id/:handle',                to: 'posts#show',      as: :frontend_post
    get  '/:handle',                    to: 'categories#show', as: :frontend_category

    match '*path' => redirect('/'), via: %i[get post]
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include Models::Handle

  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :user, counter_cache: true

  has_many :post_tags, dependent: :destroy

  has_many :tags, through: :post_tags

  has_many :category_posts, dependent: :destroy

  has_many :categories, through: :category_posts

  has_many :comments, dependent: :destroy

  has_many :images, dependent: :destroy

  has_one :post_meta, dependent: :destroy

  accepts_nested_attributes_for :post_meta

  # validations ...............................................................
  validates_presence_of :title, :content

  # callbacks .................................................................
  before_save do
    self.handle_valid(self.title, Post) if self.handle.blank?
    self.image_responsive
    self.set_images
    self.set_excerpt if self.excerpt.blank?
  end

  # scopes ....................................................................
  default_scope { order('posted_at DESC') }

  scope :publish, -> { where(status: "publish") }

  # additional config .........................................................
  paginates_per 10

  # class methods .............................................................
  # public instance methods ...................................................
  def publish?
    status == "publish"
  end

  def image_responsive
    doc = Nokogiri::HTML self.content
    doc.xpath("//img").each do |img|
      image_tag = %Q(<img src="#{img['src']}", width="#{img['width']}", height="#{img['height']}", class="img-responsive">)
      img.replace(image_tag)
    end
    self.content = doc.to_html
  end

  def set_images
    doc = Nokogiri::HTML self.content
    links = []
    doc.xpath("//img").each do |img|
      links << img['src']
    end
    Ckeditor::Picture.find_each do |picture|
      if links.include? picture.url
        self.images.find_or_create_by(picture_id: picture.id)
        links.delete(picture.url_content)
      end
      break if links.blank?
    end
    self.main_picture_id = self.images.first.try(:picture_id) unless self.main_picture_id
  end

  def set_excerpt
    self.excerpt = ActionController::Base.helpers.strip_tags(self.content.delete("\n").delete("\r")).truncate(255)
  end

  def main_picture
    Ckeditor::Picture.find_by_id self.main_picture_id
  end

  def main_picture_url
    self.main_picture_id ? self.main_picture.url : ""
  end

  def summary(length = 150)
    self.excerpt.truncate(length)
  end

  # protected instance methods ................................................
  # private instance methods ..................................................

end

app/controllers/backend/activities_controller.rb
class Backend::ActivitiesController < Backend::ApplicationController

  def index
    @activities = Activity.page params[:page]
  end

  def show
  end

  def new
  end

  def create
    if @activity = Activity.create(activity_params)
      redirect_to activities_path, flash: { success: "新增成功" }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @activity.update activity_params
      redirect_to activities_path, flash: { success: "修改成功" }
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path, flash: { success: "刪除成功" }
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :location, :start_at, :is_public, :link)
  end

end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :prepare_meta_tags, if: 'request.get?'

  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to dashboard_path, flash: { warning: exception.message }
  end

  layout 'backend_application'

  protected

  def configure_permitted_parameters
    added_attrs = %i[identify password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def prepare_meta_tags(_options = {})
    hash = {
      site: Settings.name,
      noindex: true,
      nofollow: true,
      icon: [
        { href: '/images/favicon.ico' },
        { href: '/images/apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' }
      ]
    }

    set_meta_tags hash
  end
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < Backend::ApplicationController

  def index
    @categories = Category.page params[:page]
    @category   = Category.new
  end

  def show
    @recent_posts = @category.posts.page params[:page]
  end

  def new
  end

  def create
    @category = Category.new category_params

    if @category.save
      respond_to do |format|
        format.html { redirect_to categories_path, flash: { success: "新增成功" } }
        format.json { render json: @category }
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update category_params
      redirect_to categories_path, flash: { success: "修改成功" }
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, flash: { success: "刪除成功" }
  end

  private

  def category_params
    params.require(:category).permit(:name, :handle)
  end

end

app/controllers/backend/comments_controller.rb
class Backend::CommentsController < Backend::ApplicationController

  def index
    @comments = Comment.includes(:post).page params[:page]
  end

  def edit
  end

  def update
    if @comment.update comment_params
      redirect_to comments_path, flash: { success: "修改成功" }
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to comments_path, flash: { success: "刪除成功" }
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :content, :url)
  end

end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::ApplicationController
  skip_load_and_authorize_resource

  def index
  end

end

app/controllers/backend/news_controller.rb
class Backend::NewsController < Backend::ApplicationController

  def index
    @newses = News.page params[:page]
  end

  def new
  end

  def create
    if @news = News.create(news_params)
      redirect_to news_index_path, flash: { success: "新增成功" }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @news.update news_params
      redirect_to news_index_path, flash: { success: "修改成功" }
    else
      render :edit
    end
  end

  def destroy
    @news.destroy
    redirect_to news_index_path, flash: { success: "刪除成功" }
  end

  private

  def news_params
    params.require(:news).permit(:title, :posted_at, :link)
  end

end

app/controllers/backend/posts_controller.rb
class Backend::PostsController < Backend::ApplicationController

  def index
    @posts = Post.includes(:categories, :user).page params[:page]
  end

  def new
    @post = current_user.posts.new
    @post.build_post_meta
  end

  def create
    @post = current_user.posts.new post_params

    if @post.save
      redirect_to posts_path, flash: { success: "新增成功" }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to posts_path, flash: { success: "修改成功" }
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, flash: { success: "刪除成功" }
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :excerpt, :handle, :status, :posted_at, category_ids: [], tag_ids: [],
                                 post_meta_attributes: [:keywords, :description])
  end

end

app/controllers/backend/previews_controller.rb
class Backend::PreviewsController < Backend::ApplicationController

  def create
    @preview = current_user.previews.create preview_params
    render json: @preview
  end

  private

  def preview_params
    params.require(:post).permit(:title, :content, :posted_at)
  end

end

app/controllers/backend/tags_controller.rb
class Backend::TagsController < Backend::ApplicationController

  def index
    @tags = Tag.page params[:page]
    @tag  = Tag.new
  end

  def show
    @recent_posts = @tag.posts.page params[:page]
  end

  def new
  end

  def create
    if @tag = Tag.find_or_create_by(tag_params)
      respond_to do |format|
        format.html { redirect_to tags_path, flash: { success: "新增成功" } }
        format.json { render :json => @tag }
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tag.update tag_params
      redirect_to tags_path, flash: { success: "修改成功" }
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_path, flash: { success: "刪除成功" }
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/backend/users_controller.rb
class Backend::UsersController < Backend::ApplicationController

  def index
    @users = User.page params[:page]
  end

  def show
    @recent_posts = @user.posts.page params[:page]
  end

  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), flash: { success: "新增成功" }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    params[:user].delete(:role) unless can? :manage, User

    if @user.update user_params
      redirect_to user_path, flash: { success: "修改成功" }
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, flash: { success: "刪除成功" }
  end

  private

  def user_params
    params.require(:user).permit(:email, :identify, :name, :role, :password, :password_confirmation)
  end

end

app/controllers/frontend/posts_controller.rb
class Frontend::PostsController < Frontend::ApplicationController

  def show
    @post = Post.includes(:comments, :post_meta).publish.find_by_handle params[:handle]
    redirect_to root_path, :flash => { error: "目錄已移除" } and return unless @post
    prepare_meta_tags title: @post.title,
                      description: @post.post_meta.description || @post.excerpt,
                      keywords: @post.post_meta.keywords,
                      og_type: 'article',
                      image: @post.main_picture_url
  end

end

app/helpers/backend/dashboard_helper.rb
module Backend::DashboardHelper

  def nav_link(text, path, options = {})
    icon_tag = options[:icon] ? content_tag(:span, "", class: options[:icon]) : ""
    active_icon = content_tag(:span, "", class: "glyphicon glyphicon-ok pull-right")
    is_active = is_list_active?(path)
    text = is_active ? "#{icon_tag}#{text}#{active_icon}" : "#{icon_tag}#{text}"
    link_to text.html_safe, path, data: options[:data], class: (is_active ? "text-success" : "")
  end

  def is_list_active?(path)
    current_page?(path) || is_action_match?(path)
  end

  def is_action_match?(path)
    params = Rails.application.routes.recognize_path(request.url)
    path   = Rails.application.routes.recognize_path(path)
    return false if params[:controller] != path[:controller]

    case path[:controller]
    when 'backend/tags'
      %w(index show new edit).include? params[:action]
    when 'backend/categories'
      %w(index show new edit).include? params[:action]
    when 'backend/posts'
      case path[:action]
      when 'index'
        %w(index show edit).include? params[:action]
      when 'new'
        %w(new).include? params[:action]
      else
        false
      end
    else
      false
    end
  end

end

app/helpers/backend_helper.rb
module BackendHelper

  def nav_link(text, path, options = {})
    icon_tag = options[:icon] ? content_tag(:span, "", class: options[:icon]) : ""
    active_icon = content_tag(:span, "", class: "glyphicon glyphicon-ok pull-right")
    is_active = is_list_active?(path)
    text = is_active ? "#{icon_tag}#{text}#{active_icon}" : "#{icon_tag}#{text}"
    link_to text.html_safe, path, data: options[:data], class: (is_active ? "text-success" : "")
  end

  def is_list_active?(path)
    current_page?(path) || is_action_match?(path)
  end

  def is_action_match?(path)
    params = Rails.application.routes.recognize_path(request.url)
    path   = Rails.application.routes.recognize_path(path)
    return false if params[:controller] != path[:controller]

    case path[:controller]
    when 'backend/posts'
      case path[:action]
      when 'index'
        %w(index show edit).include? params[:action]
      when 'new'
        %w(new).include? params[:action]
      else
        false
      end
    when 'backend/users'
      case path[:action]
      when 'index'
        %w(index show edit).include? params[:action]
      when 'new'
        %w(new).include? params[:action]
      else
        false
      end
    else
      params[:controller] == path[:controller]
    end
  end

end

app/views/backend/posts/_form.html.slim
= simple_form_for post, html: { id: "post_form" }, url: post do |f|
  = f.error_notification
  .row
    .col-md-6
      = f.input :title, label: false, placeholder: '標題'
    .col-md-6
      = f.input :handle, label: false, placeholder: '網址'
  = f.input :content, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } }, label: false
  .row
    .col-md-12
      = f.input :excerpt, as: :text, label: "摘要", input_html: { rows: 5 }
  .row
    .col-md-4
      .panel.panel-default
        .panel-heading 分類
        .panel-body
          .col-md-12.bottom-buffer
            = f.association :categories, as: :check_boxes, label: false
            = button_tag "新增分類", id: "new_category_btn", class: "btn btn-default", type: "button", data: { toggle: "modal", target: "#new-category" }
    .col-md-4
      .panel.panel-default
        .panel-heading 標籤
        .panel-body
          .col-md-12.bottom-buffer.top-buffer
            = content_tag :div, post.tags.pluck(:name).join(", "), id: "post_tag_names"
            .hide
              = f.association :tags, as: :check_boxes, label: false
              script
                | tag_hash =
                = raw post.tags.inject({}) { |h, e| h[e.name] = e.id; h }.to_json
    .col-md-4
      .panel.panel-default
        .panel-heading 狀態
        .panel-body
          .col-md-12.bottom-buffer.top-buffer
            = f.input :status, collection: KeyValues::Post::Status.options, selected: post.status ? post.status : :publish, label: false
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading SEO
        .panel-body
          .col-md-12.bottom-buffer.top-buffer
            = f.simple_fields_for :post_meta do |p|
              = p.input :keywords, label: "關鍵字"
              = p.input :description, as: :text, label: "描述", input_html: { rows: 5 }
  .row
    .col-md-8
      = f.input :posted_at, label: "發表時間"
    .col-md-4
      .form-group
        = f.button :submit, "儲存文章", id: "new_comment_submit", class: "btn btn-primary top-buffer margin-right-10"
        = button_tag "預覽文章", id: "preview_btn", type: "button", class: "btn btn-default top-buffer"

/ Category.new
.modal.fade role="dialog" tabindex="-1" id="new-category"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4.modal-title 請輸入預新增的分類名稱
      .modal-body
        = render "backend/categories/form", category: Category.new

/ Tag.new
.hide
  = render "backend/tags/form", tag: Tag.new

script#new-category-item type="text/x-handlebars-template"
  span.checkbox
    label for="post_category_ids_{{id}}"
      input.check_boxes.optional id="post_category_ids_{{id}}" name="post[category_ids][]" type="checkbox" value="{{id}}" checked="true"
      | {{name}}

script#new-tag-item type="text/x-handlebars-template"
  span.checkbox
    label for="post_tag_ids_{{id}}"
      input.check_boxes.optional id="post_tag_ids_{{id}}" name="post[tag_ids][]" type="checkbox" value="{{id}}" checked="true"
      | {{name}}

app/views/backend/posts/edit.html.slim
.row
  .col-md-12
    h3 編輯文章
    hr
    = render "form", post: @post

app/views/backend/posts/index.html.slim
.row
  .col-md-12
    h3 全部文章
    hr
    table.table.table-hover.table-striped
      thead
        tr
          th 標題
          th 作者
          th 分類
          th 迴響
          th 日期
          th
      tbody
        - @posts.each do |post|
          tr
            td
              = link_to post.title, edit_post_path(post), data: { no_turbolink: true }, class: "one-line-solgan", style: "max-width: 300px;"
            td
              = post.user.try(:name)
            td
              = post.categories.first.try(:name)
            td.text-center
              = post.comments.size
            td
              = post.created_at.strftime("%Y-%m-%d %M:%H")
            td.action
              = link_to "Show", frontend_post_path(post.id, post.handle), target: "_blank"
              = link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }

  .col-md-12.text-center
    = paginate @posts

app/views/backend/posts/new.html.slim
.row
  .col-md-12
    h3 新增文章
    hr
    = render "form", post: @post